/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package org.apache.grails.buildsrc

import org.gradle.api.Project
import org.gradle.api.tasks.javadoc.Groovydoc
import org.gradle.testfixtures.ProjectBuilder
import org.gradle.testkit.runner.GradleRunner
import org.gradle.testkit.runner.TaskOutcome
import spock.lang.Specification
import spock.lang.TempDir

class GroovydocEnhancerPluginSpec extends Specification {

    @TempDir
    File projectDir

    private String getGroovyVersion() {
        System.getProperty('fixture.groovy.version')
    }

    private void writeGroovydocProject() {
        new File(projectDir, 'settings.gradle').text = ''
        new File(projectDir, 'build.gradle').text = """
            plugins {
                id 'groovy'
                id 'org.apache.grails.buildsrc.groovydoc-enhancer'
            }
            repositories {
                mavenCentral()
            }
            ext.javaVersion = 21
            dependencies {
                implementation 'org.apache.groovy:groovy:${groovyVersion}'
                documentation 'org.apache.groovy:groovy:${groovyVersion}'
                documentation 'org.apache.groovy:groovy-ant:${groovyVersion}'
                documentation 'org.apache.groovy:groovy-groovydoc:${groovyVersion}'
                documentation 'org.apache.groovy:groovy-templates:${groovyVersion}'
            }
        """
        File source = new File(projectDir, 'src/main/groovy/com/example/Documented.groovy')
        source.parentFile.mkdirs()
        source.text = '''
            package com.example

            /** A documented class. */
            class Documented {
                /** A documented method. */
                void hello() {}
            }
        '''.stripIndent()
    }

    void 'groovydoc classpath includes runtime-only jars that Class.forName needs'() {
        given: 'a groovy project whose runtime-only jar is not on the compile classpath'
        Project project = ProjectBuilder.builder().withProjectDir(projectDir).build()
        project.extensions.extraProperties.set('javaVersion', 21)
        project.pluginManager.apply('groovy')
        project.pluginManager.apply(GroovydocEnhancerPlugin)

        File compileOnlyJar = new File(projectDir, 'compile-only.jar')
        File runtimeOnlyJar = new File(projectDir, 'runtime-only.jar')
        compileOnlyJar.bytes = [] as byte[]
        runtimeOnlyJar.bytes = [] as byte[]
        project.dependencies.add('compileOnly', project.files(compileOnlyJar))
        project.dependencies.add('runtimeOnly', project.files(runtimeOnlyJar))

        when: 'the groovydoc task classpath is resolved'
        Groovydoc groovydoc = project.tasks.named('groovydoc', Groovydoc).get()
        Set<File> groovydocFiles = groovydoc.classpath.files

        then: 'runtime-only jars are visible to groovydoc alongside compile-only jars'
        groovydocFiles.any { it.name == runtimeOnlyJar.name }
        groovydocFiles.any { it.name == compileOnlyJar.name }
    }

    void 'groovydoc documents the sources with the groovy the project builds against'() {
        given: 'a project whose documentation classpath pins its own groovy'
        writeGroovydocProject()

        when: 'groovydoc runs'
        def result = GradleRunner.create()
                .withProjectDir(projectDir)
                .withArguments('groovydoc')
                .withPluginClasspath()
                .build()

        then: 'the task succeeds and documents the source'
        result.task(':groovydoc').outcome == TaskOutcome.SUCCESS
        File documented = new File(projectDir, 'build/docs/groovydoc/com/example/Documented.html')
        documented.exists()

        and: "the project's groovy generated it, not the older one Gradle runs build logic on"
        documented.text.contains("Generated by groovydoc (${groovyVersion})")
    }

    void 'the groovydoc heap is the forked jvm heap, not the daemon heap'() {
        given: 'a project that would document happily on the daemon heap'
        writeGroovydocProject()

        when: 'groovydoc is given a heap no JVM can start with'
        def result = GradleRunner.create()
                .withProjectDir(projectDir)
                .withArguments('groovydoc', '-PgroovydocMaxHeapSize=1m')
                .withPluginClasspath()
                .buildAndFail()

        then: 'the groovydoc task fails on that heap while the build itself keeps running'
        result.task(':groovydoc').outcome == TaskOutcome.FAILED
        result.output.contains('Process')
    }
}
