plugins {
    id 'org.apache.grails.gradle.grails-web'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(__CURRENT_JDK__)
    }
}

tasks.register('checkCommandToolchain') {
    def toolchainVersion = providers.provider {
        def cmdTask = tasks.named('urlMappingsReport').get()
        if (cmdTask instanceof JavaExec) {
            def launcher = ((JavaExec) cmdTask).javaLauncher
            launcher.isPresent() ? String.valueOf(launcher.get().metadata.languageVersion.asInt()) : 'none'
        } else {
            'not_javaexec'
        }
    }
    doLast {
        println "CMD_TOOLCHAIN_VERSION=${toolchainVersion.get()}"
    }
}
