////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

By default interceptors will match the controllers with the same name. For example if you have an interceptor called `BookInterceptor` then all requests to the actions of the `BookController` will trigger the interceptor.

An `Interceptor` implements the link:{api}grails/artefact/Interceptor.html[Interceptor] trait and provides 3 methods that can be used to intercept requests:

[source,groovy]
----
/**
 * Executed before a matched action
 *
 * @return Whether the action should continue and execute
 */
boolean before() { true }

/**
 * Executed after the action executes but prior to view rendering
 *
 * @return True if view rendering should continue, false otherwise
 */
boolean after() { true }

/**
 * Executed after view rendering completes
 */
void afterView() {}
----

As described above the `before` method is executed prior to an action and can cancel the execution of the action by returning `false`.

The `after` method is executed after an action executes and can halt view rendering if it returns false. The `after` method can also modify the view or model using the `view` and `model` properties respectively:



[source,groovy]
----
boolean after() {
  model.foo = "bar" // add a new model attribute called 'foo'
  view = 'alternate' // render a different view called 'alternate'
  true
}
----

The `afterView` method is executed after view rendering completes. If an exception occurs, it is available using the `throwable` property of the link:{api}grails/artefact/Interceptor.html[Interceptor] trait. The property has type `Throwable`, so it can hold an `Error` as well as an `Exception`:

* An `Error` thrown by an action arrives wrapped in an exception. Use `getCause()` to reach it.
* An `Error` thrown outside the action, for example by a servlet filter, is handed to the servlet container's error page, and interceptors that match the error page's action run for that dispatch. If the error page passes the error to its model as `exception`, `throwable` holds it as the container provided it: Undertow passes the `Error` itself, while Tomcat wraps it in a `ServletException`.
