/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package grails.artefact

import org.springframework.mock.web.MockHttpServletRequest
import org.springframework.mock.web.MockHttpServletResponse
import org.springframework.web.context.WebApplicationContext
import org.springframework.web.context.request.RequestContextHolder
import spock.lang.Specification

import grails.util.GrailsWebMockUtil
import grails.web.mapping.LinkGenerator
import grails.web.mapping.mvc.RedirectEventListener
import org.grails.web.servlet.mvc.ParameterCreationListener

class ControllerRedirectSpec extends Specification {

    List<Map> linkArguments = []

    LinkGenerator linkGenerator = Stub(LinkGenerator) {
        getServerBaseURL() >> 'http://localhost:8080'
        link(_) >> { Map arguments ->
            linkArguments << arguments
            "/${arguments.action}".toString()
        }
    }

    WebApplicationContext applicationContext = Mock(WebApplicationContext)

    void setup() {
        applicationContext.getBean(LinkGenerator) >> linkGenerator
        applicationContext.getBeansOfType(ParameterCreationListener) >> [:]
    }

    void cleanup() {
        RequestContextHolder.setRequestAttributes(null)
    }

    private MockHttpServletResponse bindRequest() {
        GrailsWebMockUtil.bindMockWebRequest(applicationContext, new MockHttpServletRequest(),
                new MockHttpServletResponse()).currentResponse as MockHttpServletResponse
    }

    void 'redirect resolves the namespace declared by the controller class issuing it'() {
        given: 'a controller without a namespace and one declaring a namespace'
        def plain = new PlainRedirectController()
        def namespaced = new NamespacedRedirectController()

        when: 'each controller redirects for the first time'
        bindRequest()
        plain.redirectToIndex()
        bindRequest()
        namespaced.redirectToIndex()

        then: 'each redirect carries the namespace of its own class'
        linkArguments[0].namespace == null
        linkArguments[1].namespace == 'admin'

        when: 'the same two controller classes redirect again, now served from the namespace cache'
        bindRequest()
        namespaced.redirectToIndex()
        bindRequest()
        plain.redirectToIndex()
        bindRequest()
        new NamespacedRedirectController().redirectToIndex()

        then: 'the cached value is still the one declared by each class, never shared between them'
        linkArguments[2].namespace == 'admin'
        linkArguments[3].namespace == null
        linkArguments[4].namespace == 'admin'
    }

    void 'an explicit namespace argument is never overwritten by the declared one'() {
        given:
        def namespaced = new NamespacedRedirectController()

        when:
        def response = bindRequest()
        namespaced.redirectToIndexInNamespace('reporting')

        then:
        linkArguments[0].namespace == 'reporting'
        response.redirectedUrl == 'http://localhost:8080/index'
    }

    void 'a link generator set after the first redirect replaces the one already in use'() {
        given:
        def controller = new PlainRedirectController()
        List<Map> replacementArguments = []
        LinkGenerator replacement = Stub(LinkGenerator) {
            getServerBaseURL() >> 'http://replacement:9090'
            link(_) >> { Map arguments ->
                replacementArguments << arguments
                '/replaced'
            }
        }

        when: 'the controller redirects once, then is given a different link generator'
        bindRequest()
        controller.redirectToIndex()
        controller.setGrailsLinkGenerator(replacement)
        def response = bindRequest()
        controller.redirectToIndex()

        then: 'the second redirect is generated by the replacement'
        linkArguments.size() == 1
        replacementArguments.size() == 1
        response.redirectedUrl == 'http://replacement:9090/replaced'
    }

    void 'redirect listeners registered after the first redirect are notified'() {
        given:
        def controller = new PlainRedirectController()
        List<String> notified = []
        RedirectEventListener listener = { String url -> notified << url } as RedirectEventListener

        when: 'the controller redirects once before any listener is registered'
        bindRequest()
        controller.redirectToIndex()

        then:
        notified.isEmpty()

        when: 'a listener is registered and a further redirect is issued'
        controller.setRedirectListeners([listener])
        bindRequest()
        controller.redirectToIndex()

        then:
        notified == ['http://localhost:8080/index']
    }
}

class PlainRedirectController implements Controller {

    void redirectToIndex() {
        redirect(action: 'index')
    }
}

class NamespacedRedirectController implements Controller {

    static namespace = 'admin'

    void redirectToIndex() {
        redirect(action: 'index')
    }

    void redirectToIndexInNamespace(String explicitNamespace) {
        redirect(action: 'index', namespace: explicitNamespace)
    }
}
